name: Build Release

on:
  push:
    tags:
      - '*'
      
jobs:
  build-release:
    name: Build and Upload a release
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source
        uses: actions/checkout@v2

      - name: Create ENV
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2-)" >> "$GITHUB_ENV"
          echo "VER=$(echo $GITHUB_REF | cut -d '/' -f 3-)" >> "$GITHUB_ENV"
        
      - name: Build
        run: |
          pushd platforms/android
          ./gradlew assembleRelease
          popd

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ VER }}
          release_name: Release ${{ VER }}
          draft: false
          prerelease: false
          
      - name: Upload release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./platforms/android/build/outputs/apk/montclair-${{ VER }}-release-unsigned.apk
          asset_name: ${{ REPO }}-${{ VER }}-release-unsigned.apk
          asset_content_type: application/java-archive
